name: Luis' Homepage
author: 
  name: Luis Wolff
  email: luis-manuel.wolff@outlook.com
  twitter: https://twitter.com/LuisWolffDE
  github: https://github.com/luiswolff
  xing: http://xing.to/luis-wolff_h 